---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:18 PM
---

function featureNormalize(X)
    --FEATURENORMALIZE Normalizes the features in X
    --   FEATURENORMALIZE(X) returns a normalized version of X where
    --   the mean value of each feature is 0 and the standard deviation
    --   is 1. This is often a good preprocessing step to do when
    --   working with learning algorithms.

    local mu = X:mean(1)
    local X_norm = bsxfun(minus, X, mu)

    local sigma = X_norm:std(1)
    X_norm = bsxfun(rdivide, X_norm, sigma)

    -- ============================================================
    return X_norm, mu, sigma
end