---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:17 PM
---

function kMeansInitCentroids(X, K)
    --KMEANSINITCENTROIDS This function initializes K centroids that are to be
    --used in K-Means on the dataset X
    --   centroids = KMEANSINITCENTROIDS(X, K) returns K initial centroids to be
    --   used with the K-Means on the dataset X

    local m = X:size(1)
    local n = X:size(2)

    -- You should return this values correctly
    local centroids = torch.zeros(K, n)

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: You should set centroids to randomly chosen examples from
    --               the dataset X

    -- Initialize the centroids to be random examples
    -- Randomly reorder the indices of examples


    -- =============================================================

    return centroids
end