---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:18 PM
---

function pca(X)
    --PCA Run principal component analysis on the dataset X
    --   [U, S, X] = pca(X) computes eigenvectors of the covariance matrix of X
    --   Returns the eigenvectors U, the eigenvalues (on diagonal) in S

    -- Useful values
    local m = X:size(1)

    local U = torch.zeros(X:size(2), X:size(2))
    local S = torch.zeros(X:size(2))
    -- ====================== YOUR CODE HERE ======================
    -- Instructions: You should first compute the covariance matrix. Then, you
    --               should use the "svd" function to compute the eigenvectors
    --               and eigenvalues of the covariance matrix.
    --
    -- Note: When computing the covariance matrix, remember to divide by m (the
    --       number of examples).


    -- =========================================================================
    return U, S
end