---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 9:13 PM
---

function trainLinearReg(X, y, lambda)
    --TRAINLINEARREG Trains linear regression given a dataset (X, y) and a
    --regularization parameter lambda
    --   [theta] = TRAINLINEARREG (X, y, lambda) trains linear regression using
    --   the dataset (X, y) and regularization parameter lambda. Returns the
    --   trained parameters theta.

    -- Initialize Theta
    local initial_theta = torch.zeros(X:size(2), 1)

    -- Create "short hand" for the cost function to be minimized
    -- Now, costFunction is a function that takes in only one argument
    -- Minimize using fmincg
    local finalTheta, costHistory = optim.cg( function(curTheta)
        return linearRegCostFunction(X, y, curTheta, lambda)
    end, initial_theta, { maxIter = 200 })

    return finalTheta, costHistory
end