---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 8:55 PM
---

function randInitializeWeights(L_in, L_out)
    --RANDINITIALIZEWEIGHTS Randomly initialize the weights of a layer with L_in
    --incoming connections and L_out outgoing connections
    --   W = RANDINITIALIZEWEIGHTS(L_in, L_out) randomly initializes the weights
    --   of a layer with L_in incoming connections and L_out outgoing
    --   connections.
    --
    --   Note that W should be set to a matrix of size(L_out, 1 + L_in) as
    --   the first column of W handles the "bias" terms
    -- Instructions: Initialize W randomly so that we break the symmetry while
    --               training the neural network.
    -- Note: The first column of W corresponds to the parameters for the bias unit

    -- You need to return the following variables correctly
    local W = torch.zeros(L_out, 1 + L_in)

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Initialize W randomly so that we break the symmetry while
    --               training the neural network.
    --
    -- Note: The first column of W corresponds to the parameters for the bias unit

    -- =========================================================================

    return W
end