---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 8:50 PM
---

require 'sigmoid'

function sigmoidGradient(z)
    --SIGMOIDGRADIENT returns the gradient of the sigmoid function
    --evaluated at z
    --   g = SIGMOIDGRADIENT(z) computes the gradient of the sigmoid function
    --   evaluated at z. This should work regardless if z is a matrix or a
    --   vector. In particular, if z is a vector or matrix, you should return
    --   the gradient for each element.

    local g = torch.zeros(z:size())

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Compute the gradient of the sigmoid function evaluated at
    --               each value of z (z can be a matrix, vector or scalar).


    -- =============================================================
    return g
end