---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 8:41 PM
---

function predict(Theta1, Theta2, X)
    --PREDICT Predict the label of an input given a trained neural network
    --   p = PREDICT(Theta1, Theta2, X) outputs the predicted label of X given the
    --   trained weights of a neural network (Theta1, Theta2)

    -- Useful values
    local m = X:size(1)

    -- You need to return the following variables correctly
    local p = torch.zeros(X:size(1), 1)

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Complete the following code to make predictions using
    --               your learned neural network. You should set p to a
    --               vector containing labels between 1 to num_labels.
    --
    -- Hint: The max function might come in useful. In particular, the max
    --       function can also return the index of the max element, for more
    --       information see 'help max'. If your examples are in rows, then, you
    --       can use max(A, [], 2) to obtain the max for each row.


    -- =========================================================================

    return p
end