---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 4:26 PM
---

function computeCostMulti(X, y, theta)
    --COMPUTECOSTMULTI Compute cost for linear regression with multiple variables
    --   J = COMPUTECOSTMULTI(X, y, theta) computes the cost of using theta as the
    --   parameter for linear regression to fit the data points in X and y

    -- Initialize some useful values
    local m = length(y) -- number of training examples

    -- You need to return the following variables correctly
    local J = 0

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Compute the cost of a particular choice of theta
    --               You should set J to the cost.


    -- =========================================================================

    return J

end
