---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 4:22 PM
---

function gradientDescentMulti(X, y, theta, alpha, num_iters)
    --GRADIENTDESCENTMULTI Performs gradient descent to learn theta
    --   theta = GRADIENTDESCENTMULTI(x, y, theta, alpha, num_iters) updates theta by
    --   taking num_iters gradient steps with learning rate alpha

    -- Initialize some useful values
    local m = length(y) -- number of training examples
    local J_history = torch.zeros(1, num_iters)
    local numIterMtx = torch.zeros(1, num_iters)

    for iter = 1, num_iters do

        -- ====================== YOUR CODE HERE ======================
        -- Instructions: Perform a single gradient step on the parameter vector
        --               theta.
        --
        -- Hint: While debugging, it can be useful to print out the values
        --       of the cost function (computeCostMulti) and gradient here.
        --


        -- ============================================================

        -- Save the cost J in every iteration
        J_history[1][iter] = computeCostMulti(X, y, theta)
        numIterMtx[1][iter] = iter

    end

    return theta, J_history, numIterMtx
end