---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 4:22 PM
---

function normalEqn(X, y)
    --NORMALEQN Computes the closed-form solution to linear regression
    --   NORMALEQN(X,y) computes the closed-form solution to linear
    --   regression using the normal equations.

    local theta = torch.zeros(X:size(2), 1)

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Complete the code to compute the closed form solution
    --               to linear regression and put the result in theta.
    --


    -- ============================================================

    return theta
end