---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 4:23 PM
---

local Plot = require 'itorch.Plot'
function plotData(x, y)
    --PLOTDATA Plots the data points x and y into a new figure
    --   PLOTDATA(x,y) plots the data points and gives the figure axes labels of
    --   population and profit.

    local plot = Plot()

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Plot the training data into a figure using the
    --               "figure" and "plot" commands. Set the axes labels using
    --               the "xlabel" and "ylabel" commands. Assume the
    --               population and revenue data have been passed in
    --               as the x and y arguments of this function.
    --
    -- Hint: You can use the 'rx' option with plot to have the markers
    --       appear as red crosses. Furthermore, you can make the
    --       markers larger by using plot(..., 'rx', 'MarkerSize', 10);


    plot = Plot():circle({ 1 }, { 1 }, 'red', 'Training data') -- change this

    -- ============================================================

    plot:title('Scatter plot of training data')
    plot:xaxis('Population of City in 10,000s'):yaxis('Profit in $10,000s')
    plot:legend(true):draw()
    itorchHtml(plot, 'data.html')

    return plot
end
