---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:42 PM
---

function estimateGaussian(X)
    --ESTIMATEGAUSSIAN This function estimates the parameters of a
    --Gaussian distribution using the data in X
    --   [mu sigma2] = estimateGaussian(X),
    --   The input X is the dataset with each n-dimensional data point in one row
    --   The output is an n-dimensional vector mu, the mean of the data set
    --   and the variances sigma^2, an n x 1 vector

    local mu = torch.zeros(1, X:size(2))
    local sigma2 = torch.ones(mu:size())
    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Compute the mean of the data and the variances
    --               In particular, mu(i) should contain the mean of
    --               the data for the i-th feature and sigma2(i)
    --               should contain variance of the i-th feature.


    -- =============================================================
    return mu, sigma2
end