---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:42 PM
---

function multivariateGaussian(X, mu, Sigma2)
    --MULTIVARIATEGAUSSIAN Computes the probability density function of the
    --multivariate gaussian distribution.
    --    p = MULTIVARIATEGAUSSIAN(X, mu, Sigma2) Computes the probability
    --    density function of the examples X under the multivariate gaussian
    --    distribution with parameters mu and Sigma2. If Sigma2 is a matrix, it is
    --    treated as the covariance matrix. If Sigma2 is a vector, it is treated
    --    as the \sigma^2 values of the variances in each dimension (a diagonal
    --    covariance matrix)

    local k = length(mu)

    if Sigma2:size(2) == 1 or Sigma2:size(1) == 1 then
        Sigma2 = diag(Sigma2)
    end

    X = bsxfun(minus, X, torch.reshape(mu, 1, mu:numel()))
    local p = (2 * math.pi) ^ (-k / 2) * det(Sigma2) ^ (-0.5) * torch.exp(-0.5 * bsxfun(times, X * torch.inverse(Sigma2), X):sum(2))

    return p
end