---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:43 PM
---

function selectThreshold(yval, pval)
    --SELECTTHRESHOLD Find the best threshold (epsilon) to use for selecting
    --outliers
    --   [bestEpsilon bestF1] = SELECTTHRESHOLD(yval, pval) finds the best
    --   threshold to use for selecting outliers based on the results from a
    --   validation set (pval) and the ground truth (yval).

    local bestEpsilon = 0
    local bestF1 = 0
    local F1 = 0

    local pvalMax = pval:max()
    local pvalMin = pval:min()
    local stepsize = (pvalMax - pvalMin) / 1000
    for epsilon = pvalMin, pvalMax, stepsize do
        -- ====================== YOUR CODE HERE ======================
        -- Instructions: Compute the F1 score of choosing epsilon as the
        --               threshold and place the value in F1. The code at the
        --               end of the loop will compare the F1 score for this
        --               choice of epsilon and set it to be the best epsilon if
        --               it is better than the current choice of epsilon.
        --
        -- Note: You can use predictions = (pval < epsilon) to get a binary vector
        --       of 0's and 1's of the outlier predictions


        -- =============================================================

        if F1 > bestF1 then
            bestF1 = F1
            bestEpsilon = epsilon
        end
    end
    return bestEpsilon, bestF1
end