---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 10:42 PM
---

function visualizeFit(X, mu, sigma2)
    --VISUALIZEFIT Visualize the dataset and its estimated distribution.
    --   VISUALIZEFIT(X, p, mu, sigma2) This visualization shows you the
    --   probability density function of the Gaussian distribution. Each example
    --   has a location (x1, x2) that depends on its feature values.

    local srcNums = torch.range(0, 35, 0.5)
    local X1 = torch.reshape(srcNums, 1, srcNums:numel())
    X1 = X1:expand(X1:size(2), X1:size(2))
    local X2 = torch.reshape(srcNums, srcNums:numel(), 1)
    X2 = X2:expand(X2:size(1), X2:size(1))
    local Z = multivariateGaussian(torch.reshape(X1, X1:numel()):cat(torch.reshape(X2, X2:numel()), 2), mu, sigma2)
    Z = torch.reshape(Z, X1:size())

    --- don't know hot to plot contour, please suppliment if you know how
    gnuplot.imagesc(Z, 'color')
end