---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 9:30 PM
---

function dataset3Params(X, y, Xval, yval)
    --DATASET3PARAMS returns your choice of C and sigma for Part 3 of the exercise
    --where you select the optimal (C, sigma) learning parameters to use for SVM
    --with RBF kernel
    --   [C, sigma] = DATASET3PARAMS(X, y, Xval, yval) returns your choice of C and
    --   sigma. You should complete this function to return the optimal C and
    --   sigma based on a cross-validation set.

    -- You need to return the following variables correctly.
    local Cs = { 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30 }
    local sigmas = { 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30 }

    local bestCandSigma = {
        C = 0,
        sigma = 0
    }
    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Fill in this function to return the optimal C and sigma
    --               learning parameters found using the cross validation set.
    --               You can use svmPredict to predict the labels on the cross
    --               validation set. For example,
    --                   predictions = svmPredict(model, Xval);
    --               will return the predictions on the cross validation set.
    --  Note: You can compute the prediction error using
    --        mean(double(predictions ~= yval))


    -- =========================================================================

    return bestCandSigma.C, bestCandSigma.sigma
end