---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 9:29 PM
---

function gaussianKernel(x1, x2, sigma)
    --RBFKERNEL returns a radial basis function kernel between x1 and x2
    --   sim = gaussianKernel(x1, x2) returns a gaussian kernel between x1 and x2
    --   and returns the value in sim

    -- Ensure that x1 and x2 are column vectors
    x1 = torch.reshape(x1, x1:numel())
    x2 = torch.reshape(x2, x2:numel())

    local sim = 0
    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Fill in this function to return the similarity between x1
    --               and x2 computed using a Gaussian kernel with bandwidth
    --               sigma


    -- =============================================================

    return sim
end