---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 9:30 PM
---

function getVocabList()
    --GETVOCABLIST reads the fixed vocabulary list in vocab.txt and returns a
    --cell array of the words
    --   vocabList = GETVOCABLIST() reads the fixed vocabulary list in vocab.txt
    --   and returns a cell array of the words in vocabList.

    -- Store all dictionary words in cell array vocab{}

    -- For ease of implementation, we use a struct to map the strings => integers
    -- In practice, you'll want to use some form of hashmap
    local vocabList = {}
    local index = 1
    for line in io.lines('vocab.txt') do
        local word = string.gsub(string.gsub(line, "%S%s+(%w)", "%1"), "%d*(%S)", "%1")
        vocabList[index] = word
        vocabList[word] = index
        index = index + 1
    end

    return vocabList
end