---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 9:30 PM
---

require 'svmPredict'

function visualizeBoundary(X, y, model, plot)
    --VISUALIZEBOUNDARY plots a non-linear decision boundary learned by the SVM
    --   VISUALIZEBOUNDARYLINEAR(X, y, model) plots a non-linear decision
    --   boundary learned by the SVM and overlays the data on it

    -- Make classification predictions over a grid of values
    local data1 = X[{ {}, 1 }]
    local data2 = X[{ {}, 2 }]
    local x1plot = torch.reshape(torch.linspace(data1:min(), data1:max(), 100), 100)
    local x2plot = torch.reshape(torch.linspace(data2:min(), data2:max(), 100), 100)
    local X1, X2 = meshgrid(x1plot, x2plot)
    local vals = torch.zeros(X1:size())
    for i = 1, X1:size(2) do
        local this_X = X1[{ {}, i }]:cat(X2[{ {}, i }], 2)
        if model then
            vals[{ {}, i }] = svmPredict(model, this_X)
        end
    end

    -- Plot the SVM boundary
    --- please compare the image with 'ex6data2.html'
    --- don't know hot to plot contour, please suppliment if you know how
    gnuplot.imagesc(vals, 'color')
    --contour(X1, X2, vals, torch.Tensor({ { 0.5, 0.5 } }), 'b')
    --itorchHtml(plot, 'ex6data2.html')
end