---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 9:29 PM
---

function visualizeBoundaryLinear(X, y, model, plot)
    --VISUALIZEBOUNDARYLINEAR plots a linear decision boundary learned by the
    --SVM
    --   VISUALIZEBOUNDARYLINEAR(X, y, model) plots a linear decision boundary
    --   learned by the SVM and overlays the data on it

    local w = model.w
    local b = model.b
    local data = X[{ {}, 1 }]
    local xp = torch.linspace(data:min(), data:max(), 100)
    local yp = -(w[1][1] * xp + b) / w[2][1]
    plot:line(xp:totable(), yp:totable(), 'blue', 'Decision boundary'):redraw()
    itorchHtml(plot, 'ex6data1.html')
end