---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 5:41 PM
---

function mapFeature(X1src, X2src)
    -- MAPFEATURE Feature mapping function to polynomial features
    --
    --   MAPFEATURE(X1, X2) maps the two input features
    --   to quadratic features used in the regularization exercise.
    --
    --   Returns a new feature array with more features, comprising of
    --   X1, X2, X1.^2, X2.^2, X1*X2, X1*X2.^2, etc..
    --
    --   Inputs X1, X2 must be the same size

    local X1 = X1src
    local X2 = X2src
    if type(X1src) == "number" then
        X1 = torch.Tensor({ X1src })
    end

    if type(X2src) == "number" then
        X2 = torch.Tensor({ X2src })
    end

    local degree = 6
    local out = torch.ones(X1:size(1), 1)
    for i = 1, degree do
        for j = 0, i do
            out = out:cat((X1:clone():map(X2, function(x1, x2)
                return math.pow(x1, i - j) * math.pow(x2, j)
            end)), 2)
        end
    end
    return out
end