---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 5:43 PM
---

local Plot = require 'itorch.Plot'
function plotData(X, y)
    --PLOTDATA Plots the data points X and y into a new figure
    --   PLOTDATA(x,y) plots the data points with + for the positive examples
    --   and o for the negative examples. X is assumed to be a Mx2 matrix.

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Plot the positive and negative examples on a
    --               2D plot, using the option 'k+' for the positive
    --               examples and 'ko' for the negative examples.

    local plot = Plot():circle({ 1 }, { 1 }, 'red', 'Training data') -- change this

    -- =========================================================================

    plot:title('Plot of training data')
    plot:xaxis('Microchip Test 1'):yaxis('Microchip Test 2')
    plot:legend(true):draw()
    itorchHtml(plot, 'data_reg.html')

    return plot
end