---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shuieryin.
--- DateTime: 12/01/2018 5:38 PM
---

function sigmoid(z)
    --SIGMOID Compute sigmoid function
    --   g = SIGMOID(z) computes the sigmoid of z.

    -- You need to return the following variables correctly
    local g = torch.zeros(z:size())

    -- ====================== YOUR CODE HERE ======================
    -- Instructions: Compute the sigmoid of each value of z (z can be a matrix,
    --               vector or scalar).


    -- =============================================================
    return g
end